export default {
	Escape: 'Escape',
	
	F1: 'F1',
	F2: 'F2',
	F3: 'F3',
	F4: 'F4',
	F5: 'F5',
	F6: 'F6',
	F7: 'F7',
	F8: 'F8',
	F9: 'F9',
	F10: 'F10',
	F11: 'F11',
	F12: 'F12',
	
	Digit1: '1',
	Digit2: '2',
	Digit3: '3',
	Digit4: '4',
	Digit5: '5',
	Digit6: '6',
	Digit7: '7',
	Digit8: '8',
	Digit9: '9',
	Digit0: '0',
	
	KeyA: 'A',
	KeyB: 'B',
	KeyC: 'C',
	KeyD: 'D',
	KeyE: 'E',
	KeyF: 'F',
	KeyG: 'G',
	KeyH: 'H',
	KeyI: 'I',
	KeyJ: 'J',
	KeyK: 'K',
	KeyL: 'L',
	KeyM: 'M',
	KeyN: 'N',
	KeyO: 'O',
	KeyP: 'P',
	KeyQ: 'Q',
	KeyR: 'R',
	KeyS: 'S',
	KeyT: 'T',
	KeyU: 'U',
	KeyV: 'V',
	KeyW: 'W',
	KeyX: 'X',
	KeyY: 'Y',
	KeyZ: 'Z',
	
	Backspace: 'Backspace',
	Enter: 'Enter',
	Space: 'Space',
	Tab: 'Tab',
	
	AltLeft: 'Alt',
	AltRight: 'Alt',
	ControlLeft: 'Control',
	ControlRight: 'Control',
	MetaLeft: 'Meta',
	MetaRight: 'Meta',
	ShiftLeft: 'Shift',
	ShiftRight: 'Shift',
	
	ArrowUp: 'ArrowUp',
	ArrowDown: 'ArrowDown',
	ArrowRight: 'ArrowRight',
	ArrowLeft: 'ArrowLeft',
	
	Home: 'Home',
	End: 'End',
	PageDown: 'PageDown',
	PageUp: 'PageUp',
	Delete: 'Delete',
	
//	Unsafe keyboard shortcuts
	
	F13: 'F13',
	F14: 'F14',
	F15: 'F15',
	
	F16: 'F16',
	F17: 'F17',
	F18: 'F18',
	F19: 'F19',
	
	ScrollLock: 'ScrollLock', // Windows only
	Pause: 'Pause', // Windows only
	
	NumLock: 'Clear', // Windows NumLock: 'NumLock'
	Numpad1: '1',
	Numpad2: '2',
	Numpad3: '3',
	Numpad4: '4',
	Numpad5: '5',
	Numpad6: '6',
	Numpad7: '7',
	Numpad8: '8',
	Numpad9: '9',
	Numpad0: '0',
	NumpadEqual: '=', // Windows Equal: 'Dead'
	NumpadDivide: '/',
	NumpadMultiply: '*',
	NumpadSubtract: '-',
	NumpadAdd: '+',
	NumpadEnter: 'Enter',
	NumpadDecimal: ',',
	
	Backquote: '`',
	Backslash: '\\',
	BracketLeft: '[',
	BracketRight: ']',
	Comma: ',',
	Equal: '=',
	IntlBackslash: '§',
	Minus: '-',
	Period: '.',
	Quote: '\'',
	Semicolon: ';',
	Slash: '/'
}